//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharrityAuction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharrityAuction.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեր մասին.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Դր..
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԿԱՏԱՐԵԼ ՀԱՅՏ.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գնորդ.
        /// </summary>
        public static string Buyer {
            get {
                return ResourceManager.GetString("Buyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գումարը.
        /// </summary>
        public static string CharityMoney {
            get {
                return ResourceManager.GetString("CharityMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Նպատակը.
        /// </summary>
        public static string CharityPurpose {
            get {
                return ResourceManager.GetString("CharityPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԸՆԹԱՑԻԿ ԱՐԺԵՔԸ.
        /// </summary>
        public static string CurrentBid {
            get {
                return ResourceManager.GetString("CurrentBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to օր.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հայտերի ընդունման վերջնաժամկետը.
        /// </summary>
        public static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր էլ. հասցեին ուղարկվել է գաղտնաբառը վերականգնող նամակ.
        /// </summary>
        public static string EmailCheck {
            get {
                return ResourceManager.GetString("EmailCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Շնորհավորում ենք: Դուք հաղթել եք բարեգործական Աճուրդում: Խնդրում ենք մինչև _______________ կատարել _________________ դրամ վճարումը Ձեր նախընտրած եղանակով(քարտով, կանխիկ, փոխանցում)` հաղթած ԼՈՏ-ը ստանալու համար:
        ///Կարող եք նաև զանգահարել XXX-XX-XX-XX հեռախոսահամարով, և մեր աշխատակիցը ավելի մանրամասն տեղեկատվություն կտրամադրի Ձեզ վճարման կարգի և ԼՈՏ-ի ստացման պայմանների մասին:Վճարելու համար անցեք հետևյալ  &lt;a href=&apos;{0}&apos;&gt;հղումով&lt;/a&gt;.
        /// </summary>
        public static string EmailConfirmationBid {
            get {
                return ResourceManager.GetString("EmailConfirmationBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վերականգնել.
        /// </summary>
        public static string EmailReset {
            get {
                return ResourceManager.GetString("EmailReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ավարտված.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մուտքագրեք էլ. հասցեն.
        /// </summary>
        public static string EnterMail {
            get {
                return ResourceManager.GetString("EnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԳՆԱՀԱՏՎԱԾ ԱՐԺԵՔԸ.
        /// </summary>
        public static string EstimatedValue {
            get {
                return ResourceManager.GetString("EstimatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մոռացել եք գաղտնաբառը.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ժ..
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Էլ. հասցեն կամ գաղտնաբառը սխալ են.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վերջին հայտերը.
        /// </summary>
        public static string LastBids {
            get {
                return ResourceManager.GetString("LastBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մուտք.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Չունեք հաշիվ.
        /// </summary>
        public static string LoginDontHave {
            get {
                return ResourceManager.GetString("LoginDontHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ստեղծեք.
        /// </summary>
        public static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to նոր հաշիվ.
        /// </summary>
        public static string LoginRegisterAsNewUser {
            get {
                return ResourceManager.GetString("LoginRegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մուտք գործեք մասնակցելու համար.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վերջնաժամկետ.
        /// </summary>
        public static string LotDate {
            get {
                return ResourceManager.GetString("LotDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Տվյալ աճուրդն .
        /// </summary>
        public static string LotDayPassed {
            get {
                return ResourceManager.GetString("LotDayPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Լոթի նկարագիր.
        /// </summary>
        public static string LotDetails {
            get {
                return ResourceManager.GetString("LotDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ամսաթիվ.
        /// </summary>
        public static string LotOccureDate {
            get {
                return ResourceManager.GetString("LotOccureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կանոններ և կանոնակարգեր.
        /// </summary>
        public static string LotRulesRegulations {
            get {
                return ResourceManager.GetString("LotRulesRegulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Արժեք.
        /// </summary>
        public static string LotValue {
            get {
                return ResourceManager.GetString("LotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գլխավոր.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մասնակցել.
        /// </summary>
        public static string MainDetails {
            get {
                return ResourceManager.GetString("MainDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գործընկերներ.
        /// </summary>
        public static string MenuCoWorkers {
            get {
                return ResourceManager.GetString("MenuCoWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բարի գնորդներ.
        /// </summary>
        public static string MenuGoodBuyers {
            get {
                return ResourceManager.GetString("MenuGoodBuyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեդիա.
        /// </summary>
        public static string MenuMedia {
            get {
                return ResourceManager.GetString("MenuMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to վճարում.
        /// </summary>
        public static string MenuPayment {
            get {
                return ResourceManager.GetString("MenuPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ֆոտո.
        /// </summary>
        public static string MenuPhoto {
            get {
                return ResourceManager.GetString("MenuPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաշվետվություն.
        /// </summary>
        public static string MenuReport {
            get {
                return ResourceManager.GetString("MenuReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կանոնները.
        /// </summary>
        public static string MenuRules {
            get {
                return ResourceManager.GetString("MenuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Աստղեր.
        /// </summary>
        public static string MenuStars {
            get {
                return ResourceManager.GetString("MenuStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վիդեո.
        /// </summary>
        public static string MenuVideo {
            get {
                return ResourceManager.GetString("MenuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ում ենք օգնում.
        /// </summary>
        public static string MenuWhoWeHelp {
            get {
                return ResourceManager.GetString("MenuWhoWeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Նշված գումարը փոքր է թույլատրելի շեմից.
        /// </summary>
        public static string MinBidAlert {
            get {
                return ResourceManager.GetString("MinBidAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ր..
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բարեգործական աճուրդ.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Նորություններ.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to կարդալ ավելին.....
        /// </summary>
        public static string NewsReadMore {
            get {
                return ResourceManager.GetString("NewsReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to արդեն ավարտվել է.
        /// </summary>
        public static string PassedSecondString {
            get {
                return ResourceManager.GetString("PassedSecondString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գաղտնաբառի վերականգնում.
        /// </summary>
        public static string PasswodReset {
            get {
                return ResourceManager.GetString("PasswodReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր վճարումը կատարված է մեր աշխատակիցները կկապվնեն ձեզ հետ:&lt;br&gt; Ձեր հայտի համարն է  &lt;b&gt;#{0}&lt;/b&gt;.
        /// </summary>
        public static string PaymentApproved {
            get {
                return ResourceManager.GetString("PaymentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Էլ. հասցեն հաստատված չէ, մուտք գործելու համար հաստատեք էլ. հասցեն .
        /// </summary>
        public static string PleaseConfirm {
            get {
                return ResourceManager.GetString("PleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կանոններ.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Իմ էջը.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Գրանցվել.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կրկնեք գաղտնաբառը.
        /// </summary>
        public static string RegistrationConfirmPassword {
            get {
                return ResourceManager.GetString("RegistrationConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Էլ.հասցե.
        /// </summary>
        public static string RegistrationEmail {
            get {
                return ResourceManager.GetString("RegistrationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} դաշտը դատարկ է.
        /// </summary>
        public static string RegistrationErrorMessage {
            get {
                return ResourceManager.GetString("RegistrationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ազգանուն.
        /// </summary>
        public static string RegistrationLastName {
            get {
                return ResourceManager.GetString("RegistrationLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Անուն.
        /// </summary>
        public static string RegistrationName {
            get {
                return ResourceManager.GetString("RegistrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ստեղծել կեղծանուն.
        /// </summary>
        public static string RegistrationNickname {
            get {
                return ResourceManager.GetString("RegistrationNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ցուցադրվելու է ձեր գնումներում.
        /// </summary>
        public static string RegistrationNicknameInfo {
            get {
                return ResourceManager.GetString("RegistrationNicknameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գաղտնաբառ.
        /// </summary>
        public static string RegistrationPassword {
            get {
                return ResourceManager.GetString("RegistrationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գաղտնաբառը պետք է լինի {2} նիշից ոչ պակաս.
        /// </summary>
        public static string RegistrationPasswordError {
            get {
                return ResourceManager.GetString("RegistrationPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գաղտնաբառերը չեն համընկնում.
        /// </summary>
        public static string RegistrationPasswordNotMatching {
            get {
                return ResourceManager.GetString("RegistrationPasswordNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հեռախոսահամար.
        /// </summary>
        public static string RegistrationPhone {
            get {
                return ResourceManager.GetString("RegistrationPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ես կարդացել եմ և ընդունում եմ օգտագործման &lt;a href=&apos;/Home/Privacy&apos; style=&quot;color:#0973bf&quot;&gt;կանոնոնները&lt;/a&gt;.
        /// </summary>
        public static string RegistrationPrivacy {
            get {
                return ResourceManager.GetString("RegistrationPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Լրացրեք պահանջվող դաշտերը.
        /// </summary>
        public static string RegistrationRequiredFields {
            get {
                return ResourceManager.GetString("RegistrationRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գրանցվիր մասնակցելու համար.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՄՆԱՑԵԼ Է.
        /// </summary>
        public static string Remains {
            get {
                return ResourceManager.GetString("Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հիշել.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Փնտրել.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Որոնման արդյունքներ:.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պահպանել.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Խմբագրեք ձեր անձնական տվյալները.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Արժեքը.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
