//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharrityAuction {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharrityAuction.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեր մասին.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Դրամ.
        /// </summary>
        public static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՀԱՅՏ.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԸՆԹԱՑԻԿ ՀԱՅՏԵՐ.
        /// </summary>
        public static string CurrentBid {
            get {
                return ResourceManager.GetString("CurrentBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to օր.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հայտերի ընդունման վերջնաժամկետը.
        /// </summary>
        public static string DeadLine {
            get {
                return ResourceManager.GetString("DeadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Շնորհավորում ենք: Դուք հաղթել եք բարեգործական Աճուրդում: Խնդրում ենք մինչև _______________ կատարել _________________ դրամ վճարումը Ձեր նախընտրած եղանակով(քարտով, կանխիկ, փոխանցում)` հաղթած ԼՈՏ-ը ստանալու համար:
        ///Կարող եք նաև զանգահարել XXX-XX-XX-XX հեռախոսահամարով, և մեր աշխատակիցը ավելի մանրամասն տեղեկատվություն կտրամադրի Ձեզ վճարման կարգի և ԼՈՏ-ի ստացման պայմանների մասին:Վճարելու համար անցեք հետևյալ  &lt;a href=&apos;{0}&apos;&gt;հղումով&lt;/a&gt;.
        /// </summary>
        public static string EmailConfirmationBid {
            get {
                return ResourceManager.GetString("EmailConfirmationBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԳՆԱՀԱՏՎԱԾ ԱՐԺԵՔԸ.
        /// </summary>
        public static string EstimatedValue {
            get {
                return ResourceManager.GetString("EstimatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ժամ.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վերջին հայտերը.
        /// </summary>
        public static string LastBids {
            get {
                return ResourceManager.GetString("LastBids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մուտք.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գլխավոր.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մասնակցել.
        /// </summary>
        public static string MainDetails {
            get {
                return ResourceManager.GetString("MainDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գործընկերներ.
        /// </summary>
        public static string MenuCoWorkers {
            get {
                return ResourceManager.GetString("MenuCoWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բարի գնորդներ.
        /// </summary>
        public static string MenuGoodBuyers {
            get {
                return ResourceManager.GetString("MenuGoodBuyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Մեդիա.
        /// </summary>
        public static string MenuMedia {
            get {
                return ResourceManager.GetString("MenuMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to վճարում.
        /// </summary>
        public static string MenuPayment {
            get {
                return ResourceManager.GetString("MenuPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ֆոտո.
        /// </summary>
        public static string MenuPhoto {
            get {
                return ResourceManager.GetString("MenuPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հաշվետվություն.
        /// </summary>
        public static string MenuReport {
            get {
                return ResourceManager.GetString("MenuReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կանոնները.
        /// </summary>
        public static string MenuRules {
            get {
                return ResourceManager.GetString("MenuRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Աստղեր.
        /// </summary>
        public static string MenuStars {
            get {
                return ResourceManager.GetString("MenuStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Վիդեո.
        /// </summary>
        public static string MenuVideo {
            get {
                return ResourceManager.GetString("MenuVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ում ենք օգնում.
        /// </summary>
        public static string MenuWhoWeHelp {
            get {
                return ResourceManager.GetString("MenuWhoWeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to րոպե.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Բարեգործական աճուրդ.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Նորություններ.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր վճարումը կատարված է մեր աշխատակիցները կկապվնեն ձեզ հետ:&lt;br&gt; Ձեր հայտի համարն է  &lt;b&gt;#{0}&lt;/b&gt;.
        /// </summary>
        public static string PaymentApproved {
            get {
                return ResourceManager.GetString("PaymentApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Իմ էջը.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Գրանցվել.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՄՆԱՑԵԼ Է.
        /// </summary>
        public static string Remains {
            get {
                return ResourceManager.GetString("Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Արժեքը.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
